WIP: add elasticsearch callback
NSLS-II/databroker-elasticsearch pull request #1
Opened 2018-10-01 17:02 UTC by CJ-Wright

Still needs tests and a way to setup elastic on travis-ci

2018-10-04 20:39 UTC, tacaswell commented
https://docs.travis-ci.com/user/database-setup/#elasticsearch <- how to turn elastic on.

2018-10-11 15:00 UTC, pavoljuhas commented on setup.py
> +    version='0.3.6',
Is there any particular reason to use `0.3.6`?
I feel a brand new project should start at `0.0.1`.

2018-10-11 15:54 UTC, CJ-Wright commented on setup.py
> +    version='0.3.6',
I copy pasted this from another project. Before we run a release I'd start with `0.0.1`.

2018-10-15 16:28 UTC, pavoljuhas commented
I propose we merge this PR after adding my small correction below.
We can then open new PRs for #2 and for adding a travis test.

@stuartcampbell -- can I please have a push access for this repo?

----

@CJ-Wright -- can you please do a fast-forward of the following?

The following changes since commit 1144cfb3f2a368464e66ccada9fda678da08584f:

  add callback and setup.py (2018-10-01 13:02:06 -0400)

are available in the Git repository at:

  https://github.com/pavoljuhas/databroker-elasticsearch.git
  in branch es-01

for you to fetch changes up to 3078564283b3292ff4676ca1a9a47d3e2575d904:

  REL: reset initial version to 0.0.1 (2018-10-15 12:07:12 -0400)

----------------------------------------------------------------
Pavol Juhas (1):
      REL: reset initial version to 0.0.1

 db_es/__init__.py | 0
 setup.py          | 2 +-
 2 files changed, 1 insertion(+), 1 deletion(-)
 create mode 100644 db_es/__init__.py

2018-10-15 16:47 UTC, CJ-Wright commented
This PR doesn't have tests or a CI running the tests, I do not want to merge this until those two things are done.

2018-10-15 16:57 UTC, CJ-Wright commented
@stuartcampbell I also need permissions on this.

2018-10-15 18:11 UTC, stuartcampbell commented
@CJ-Wright looks like you are already an admin, you just need to accept the invite

2018-10-15 18:30 UTC, CJ-Wright commented
Hmm, ok that didn't show up on my github page. I've got it now.

2018-10-19 19:11 UTC, CJ-Wright commented
@pavoljuhas does Elasticsearch automatically make a new index if we ask for an index and it doesn't exist or do we need to initialize it?

2018-10-19 20:09 UTC, pavoljuhas commented
`db_es/__init__.py` is still missing therefore `python setup.py install` does not work.

Please add an empty `db_es/__init__.py`.

2018-10-21 19:10 UTC, CJ-Wright commented
cycle for ci

2018-10-21 22:06 UTC, CJ-Wright commented
@pavoljuhas how does the python elasticsearch API work?

2018-10-23 01:01 UTC, CJ-Wright commented
Cycle for ci

2018-10-23 19:25 UTC, CJ-Wright commented
I think this is ready to go, there are more things to do for this `sphinx/gh_pages/doctr/rever/packaging` but I don't want to have this PR wait on those as much since they are slightly separate concerns. We have baseline level functionality and tests for that functionality, with docstrings and two examples for the common usecases.

2018-10-23 22:54 UTC, pavoljuhas commented
Please fix these whitespace issues and we can merge.

```patch
$ git diff --check master HEAD
db_es/callback.py:74: trailing whitespace.
+    
db_es/callback.py:77: trailing whitespace.
+   
db_es/callback.py:88: trailing whitespace.
+    
db_es/callback.py:95: trailing whitespace.
+    
db_es/callback.py:105: trailing whitespace.
+    
```

2018-10-24 14:06 UTC, pavoljuhas requested changes
Nope.  Please make sure `git diff --check master` passes without complaints.

2018-10-24 15:15 UTC, pavoljuhas approved these changes

2018-10-24 15:16 UTC, CJ-Wright commented
Feel free to merge when ready.

2018-10-24 15:21 UTC, merged